//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 03:26:19 PM PDT 
//


package com.fed.saml.trust.metadata.objects;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fed.saml.metadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _X509IssuerName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509IssuerName");
    private final static QName _SignatureValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureValue");
    private final static QName _DigestValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestValue");
    private final static QName _X509SubjectName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SubjectName");
    private final static QName _X509Certificate_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Certificate");
    private final static QName _X509SerialNumber_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SerialNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fed.saml.metadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Transforms }
     * 
     */
    public Transforms createTransforms() {
        return new Transforms();
    }

    /**
     * Create an instance of {@link Transform }
     * 
     */
    public Transform createTransform() {
        return new Transform();
    }

    /**
     * Create an instance of {@link DigestMethod }
     * 
     */
    public DigestMethod createDigestMethod() {
        return new DigestMethod();
    }

    /**
     * Create an instance of {@link CanonicalizationMethod }
     * 
     */
    public CanonicalizationMethod createCanonicalizationMethod() {
        return new CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link X509Data }
     * 
     */
    public X509Data createX509Data() {
        return new X509Data();
    }

    /**
     * Create an instance of {@link X509IssuerSerial }
     * 
     */
    public X509IssuerSerial createX509IssuerSerial() {
        return new X509IssuerSerial();
    }

    /**
     * Create an instance of {@link SignedInfo }
     * 
     */
    public SignedInfo createSignedInfo() {
        return new SignedInfo();
    }

    /**
     * Create an instance of {@link SignatureMethod }
     * 
     */
    public SignatureMethod createSignatureMethod() {
        return new SignatureMethod();
    }

    /**
     * Create an instance of {@link KeyInfo }
     * 
     */
    public KeyInfo createKeyInfo() {
        return new KeyInfo();
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link EntityDescriptor }
     * 
     */
    public EntityDescriptor createEntityDescriptor() {
        return new EntityDescriptor();
    }

    /**
     * Create an instance of {@link SPSSODescriptor }
     * 
     */
    public SPSSODescriptor createSPSSODescriptor() {
        return new SPSSODescriptor();
    }

    /**
     * Create an instance of {@link KeyDescriptor }
     * 
     */
    public KeyDescriptor createKeyDescriptor() {
        return new KeyDescriptor();
    }

    /**
     * Create an instance of {@link EncryptionMethod }
     * 
     */
    public EncryptionMethod createEncryptionMethod() {
        return new EncryptionMethod();
    }

    /**
     * Create an instance of {@link SingleLogoutService }
     * 
     */
    public SingleLogoutService createSingleLogoutService() {
        return new SingleLogoutService();
    }

    /**
     * Create an instance of {@link AssertionConsumerService }
     * 
     */
    public AssertionConsumerService createAssertionConsumerService() {
        return new AssertionConsumerService();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509IssuerName")
    public JAXBElement<String> createX509IssuerName(String value) {
        return new JAXBElement<String>(_X509IssuerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureValue")
    public JAXBElement<byte[]> createSignatureValue(byte[] value) {
        return new JAXBElement<byte[]>(_SignatureValue_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestValue")
    public JAXBElement<String> createDigestValue(String value) {
        return new JAXBElement<String>(_DigestValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SubjectName")
    public JAXBElement<String> createX509SubjectName(String value) {
        return new JAXBElement<String>(_X509SubjectName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Certificate")
    public JAXBElement<byte[]> createX509Certificate(byte[] value) {
        return new JAXBElement<byte[]>(_X509Certificate_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SerialNumber")
    public JAXBElement<BigInteger> createX509SerialNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_X509SerialNumber_QNAME, BigInteger.class, null, value);
    }

}
