//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 03:26:19 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://www.w3.org/2000/09/xmldsig#", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
		xmlns = {
				@XmlNs(prefix="md", namespaceURI="urn:oasis:names:tc:SAML:2.0:metadata"),
				@XmlNs(prefix="dsig", namespaceURI="http://www.w3.org/2000/09/xmldsig#")		        		        
		    })
package com.fed.saml.trust.metadata.objects;

import javax.xml.bind.annotation.XmlNs;