//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.18 at 03:26:19 PM PDT 
//


package com.fed.saml.trust.metadata.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509Certificate"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509IssuerSerial"/>
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509SubjectName"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "x509Certificate",
    "x509IssuerSerial",
    "x509SubjectName"
})
@XmlRootElement(name = "X509Data")
public class X509Data {

    @XmlElement(name = "X509Certificate", required = true)
    protected byte[] x509Certificate;
    @XmlElement(name = "X509IssuerSerial")
    protected X509IssuerSerial x509IssuerSerial;
    @XmlElement(name = "X509SubjectName")
    protected String x509SubjectName;

    /**
     * Gets the value of the x509Certificate property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getX509Certificate() {
        return x509Certificate;
    }

    /**
     * Sets the value of the x509Certificate property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setX509Certificate(byte[] value) {
        this.x509Certificate = value;
    }

    /**
     * Gets the value of the x509IssuerSerial property.
     * 
     * @return
     *     possible object is
     *     {@link X509IssuerSerial }
     *     
     */
    public X509IssuerSerial getX509IssuerSerial() {
        return x509IssuerSerial;
    }

    /**
     * Sets the value of the x509IssuerSerial property.
     * 
     * @param value
     *     allowed object is
     *     {@link X509IssuerSerial }
     *     
     */
    public void setX509IssuerSerial(X509IssuerSerial value) {
        this.x509IssuerSerial = value;
    }

    /**
     * Gets the value of the x509SubjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX509SubjectName() {
        return x509SubjectName;
    }

    /**
     * Sets the value of the x509SubjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX509SubjectName(String value) {
        this.x509SubjectName = value;
    }

}
